MERGE (s:Subject {id:'demo_001'})
MERGE (g:Feature {name:'Glucose'})
MERGE (b:Feature {name:'BMI'})
MERGE (a:Feature {name:'Age'})
MERGE (bp:Feature {name:'BloodPressure'})
MERGE (t:TargetConcept {name:'Diabetes Outcome'})
MERGE (m:MLModel {name:'Logistic Regression'})
MERGE (p:Prediction {task:'Diabetes Classification'})
MERGE (s)-[:HAS_FEATURE]->(g)
MERGE (s)-[:HAS_FEATURE]->(b)
MERGE (s)-[:HAS_FEATURE]->(a)
MERGE (s)-[:HAS_FEATURE]->(bp)
MERGE (s)-[:HAS_PREDICTION]->(p)
MERGE (p)-[:PREDICTED_BY]->(m)
MERGE (p)-[:ABOUT]->(t);