MERGE (h:House {id:'demo_H01'})
MERGE (a:Feature {name:'Area'})
MERGE (f:Feature {name:'Frontage'})
MERGE (r:Feature {name:'Access Road'})
MERGE (b:Feature {name:'Bedrooms'})
MERGE (t:TargetConcept {name:'Price'})
MERGE (m:MLModel {name:'Gradient Boosting Regressor'})
MERGE (p:Prediction {task:'Vietnam House Price Regression'})
MERGE (h)-[:HAS_FEATURE]->(a)
MERGE (h)-[:HAS_FEATURE]->(f)
MERGE (h)-[:HAS_FEATURE]->(r)
MERGE (h)-[:HAS_FEATURE]->(b)
MERGE (h)-[:HAS_PREDICTION]->(p)
MERGE (p)-[:PREDICTED_BY]->(m)
MERGE (p)-[:ABOUT]->(t);